pacman -Syu --noconfirm \
       git \
       sway \
       swayidle \
       swaylock \
       xorg-server \
       xorg-xinit \
       xorg-xev \
       xorg-randr \
       i3-wm \
       i3status \
       dialog \
       base-devel \
       which \
       sudo \
       man \
       bc \
       tree \
       fd \
       ripgrep \
       htop \
       wget \
       pango \
       dnsutils \
       usbutils \
       ntp \
       iptables-nft \
       adobe-source-code-pro-fonts \
       emacs \
       zsh \
       alacritty \
       tmux \
       grim \
       slurp \
       alsa-utils \
       light \
       bluez-utils \
       transmission-cli \
       acpi \
       firefox \
       yq \
       go \
       python \
       python-pip \
       python-virtualenv \
       gcc-fortran \
       r \
       ghc \
       stack \
       tk \
       hub \
       gist \
       kubectl \
       helm \
       texlive-bin \
       biber \
       gdal \
       librdkafka \
       docker \
       docker-compose \
       flatpak \
       borg \
       openfortivpn \
       aspell-en \
       openvpn \
       networkmanager-openvpn \
       transmission-cli \
       imv \
       vlc \
       pulseaudio-alsa \
       pulseaudio-bluetooth \
       imagemagick \
       obs-studio \
       ppp \
       pdftk \
       mupdf \
       qgis \
       python-gdal \
       xdg-user-dirs \
       android-tools \
       xdg-desktop-portal-wlr \
       luajit \
       bluetui \
       rust-analyzer \
       bemenu \
       bemenu-wayland \
       swaybg \
       jq \
       playerctl \
       keyd
