pacman -Syu --noconfirm \
       git \
       sway \
       dialog \
       wifi-menu \
       base-devel \
       which \
       sudo \
       man \
       bc \
       tree \
       htop \
       wget \
       pango \
       dsnutils \
       usbutils \
       ntp \
       iptables-nft \
       adobe-source-code-pro-fonts \
       emacs \
       zsh \
       alacritty \
       tmux \
       grim \
       slurp \
       alsa-utils \
       light \
       bluez-utils \
       transmission-cli \
       yq \
       go \
       python \
       python-pip \
       python-virtualenv \
       r \
       ghc \
       stack \
       tk \
       hub \
       gist \
       kubectl \
       texlive-most \
       biber \
       gdal \
       pandoc \
       librdkafka \
       docker \
       flatpak \
       borg \
       openfortivpn \
       aspell-en \
       openvpn \
       networkmanager-openvpn \
       transmission-cli \
       imv \
       vlc \
       pulseaudio-alsa \
       pulseaudio-bluetooth \
       imagemagick \
       obs-studio \
       ppp \
       pdftk \
       qgis \
       python-gdal
