# Paths aconfmgr should never capture.
#
# Three kinds of thing belong here, and only these:
#   - state and caches: rebuilt by software, not config you chose
#   - secrets: this repo is pushed to git; they come back from borg's /etc instead
#   - per-machine identity: created fresh by each install (disk UUIDs, machine-id)
#
# Anything else that shows up in 99-unsorted.sh is either real config (move it
# into a group file) or a new kind of noise (add it here with a reason).

### Not config: other trees
IgnorePath '/home/*'            # comes back from borg
IgnorePath '/root/*'            # holds /root/.borg-passphrase
IgnorePath '/lost+found/*'
IgnorePath '/swapfile'          # created by hand, see hibernation.md
IgnorePath '/boot/*'            # kernel/initramfs are generated; ucode is packaged

### State and caches under /var
IgnorePath '/var/lib/*'         # service state: docker images, snapd, flatpak, ollama models, ...
IgnorePath '/var/cache/*'
IgnorePath '/var/log/*'
IgnorePath '/var/tmp/*'
IgnorePath '/var/spool/*'
IgnorePath '/var/db/*'
IgnorePath '/var/.updated'

### Generated under /usr and /opt
IgnorePath '/usr/lib/modules/*/modules.*'
IgnorePath '/usr/lib/locale/locale-archive'
IgnorePath '/usr/lib/gdk-pixbuf-2.0/*/loaders.cache'
IgnorePath '/usr/lib/gio/modules/giomodule.cache'
IgnorePath '/usr/share/mime/*'
IgnorePath '/usr/share/info/dir'
IgnorePath '/usr/share/applications/mimeinfo.cache'
IgnorePath '/usr/share/glib-2.0/schemas/gschemas.compiled'
IgnorePath '/usr/share/icons/*/icon-theme.cache'
IgnorePath '/usr/lib/python3*/site-packages/*/__pycache__/*'
IgnorePath '/opt/containerd/*'  # docker runtime state

### Installed outside pacman (documented in README, not tracked file-by-file)
IgnorePath '/usr/local/texlive/*'   # TeX Live via install-tl, see tex.sh
IgnorePath '/usr/local/share/*'
IgnorePath '/usr/local/bin/kubent'  # downloaded binary, see README

### Generated under /etc
IgnorePath '/etc/.pwd.lock'
IgnorePath '/etc/.updated'
IgnorePath '/etc/ld.so.cache'
IgnorePath '/etc/ssl/certs/*'
IgnorePath '/etc/ca-certificates/extracted/*'
IgnorePath '/etc/pacman.d/gnupg/*'
IgnorePath '/etc/fonts/conf.d/*'
IgnorePath '/etc/dconf/db/*'
IgnorePath '/etc/mkinitcpio.d/*'     # presets regenerated by the linux package
IgnorePath '/etc/os-release'
IgnorePath '/etc/mtab'
IgnorePath '/etc/adjtime'
IgnorePath '/etc/resolv.conf'        # written by NetworkManager / tailscale / mullvad

# Leftovers from upgrades and hand edits. Merge .pacnew with `pacdiff`, not here.
IgnorePath '/etc/*.pacnew'
IgnorePath '/etc/*.pacsave'
IgnorePath '/etc/*.bak*'
IgnorePath '/etc/*.backup'

### Per-machine identity: created by each install
IgnorePath '/etc/machine-id'
IgnorePath '/etc/fstab'
IgnorePath '/etc/crypttab'
IgnorePath '/etc/tpm2-tss/*'

### Secrets: never in git; restored from borg's copy of /etc
IgnorePath '/etc/shadow*'
IgnorePath '/etc/gshadow*'
IgnorePath '/etc/passwd-'
IgnorePath '/etc/group-'
IgnorePath '/etc/ssh/ssh_host_*'
IgnorePath '/etc/NetworkManager/system-connections/*'
IgnorePath '/etc/mullvad-vpn/*'
IgnorePath '/etc/docker/key.json'

### Added after the first save (2026-09-30)

# More generated caches and indexes
IgnorePath '/usr/share/fonts/*/fonts.dir'
IgnorePath '/usr/share/fonts/*/fonts.scale'
IgnorePath '/usr/lib/gconv/gconv-modules.cache'
IgnorePath '/usr/lib/gtk-*/*/immodules.cache'
IgnorePath '/usr/lib/udev/hwdb.bin'
IgnorePath '/usr/lib/vlc/plugins/plugins.dat'
IgnorePath '/usr/share/texmf*/ls-R'
IgnorePath '/etc/texmf/ls-R'
IgnorePath '/usr/share/perl5/vendor_perl/XML/SAX/ParserDetails.ini'
IgnorePath '/etc/xml/catalog'
IgnorePath '/usr/lib/jvm/default*'          # set by archlinux-java
IgnorePath '/usr/lib/libvsscript.so'
IgnorePath '/usr/share/python-validity/*'   # sensor calibration, per-device

# Leftover from Python 3.8 (an old manual pip install). Safe to delete by hand.
IgnorePath '/usr/lib/python3.8/*'


# Permissions set by package install scripts, not by me
IgnorePath '/lost+found'
IgnorePath '/usr/lib/utempter/utempter'
IgnorePath '/usr/bin/mullvad-exclude'
IgnorePath '/etc/cni'
IgnorePath '/etc/bluetooth'

# Empty directories that packages expect but don't own
IgnorePath '/etc/audisp'
IgnorePath '/etc/audit/*'
IgnorePath '/etc/dbus-1/system.d'

# Users and groups: created at install time, see README. UIDs/GIDs differ per
# machine depending on package install order, so these files must not be copied.
IgnorePath '/etc/passwd*'
IgnorePath '/etc/group'
IgnorePath '/etc/shells'                    # maintained by shell packages' hooks

# One-off backups
IgnorePath '/etc/resolv.pre-tailscale-backup.conf'
IgnorePath '/usr/local/sbin/*.bak*'
